name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Front-end Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint code
        working-directory: frontend
        run: npm run lint

      - name: Build production bundle
        working-directory: frontend
        run: npm run build

  backend:
    name: Back-end Build & Test
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore packages
        working-directory: backend
        run: dotnet restore

      - name: Build solution
        working-directory: backend
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        working-directory: backend
        env:
          VSTEST_CONNECTION_TIMEOUT: 300
        run: |